can/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidates.urls', namespace='candidate')),
    path('', include('recruiters.urls', namespace='recruiters')),
    path('tasks/', include('tasks.urls', namespace='task')),
]

candidates/urls.py
from django.urls import path, include
from candidates.views import show_all_candidate, show_tasks, task_solution

app_name = 'candidate'


urlpatterns = [
    path('', show_all_candidate, name='show_all_candidate'),
    path('candidate-tasks/<int:candidate_id>/', show_tasks, name='show_tasks'),
    path('task-solution/<int:task_id>/', task_solution, name='task_solution'),

]

candidates/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Candidate(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    class Meta:
        index_together = (('id',),)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('show_candidate', args=[self.id])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

candidates/forms.py
from django import forms

from tasks.models import Task


class TaskSolutionForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['answer']

candidates/views.py
from django.shortcuts import render, redirect

from candidates.forms import TaskSolutionForm
from candidates.models import Candidate

# Create your views here.
from tasks.models import Task


def show_all_candidate(request):
    candidates = Candidate.objects.all()
    return render(request, 'candidates/list_candidate.html', {'candidates': candidates})


def show_tasks(request, candidate_id):
    candidate = Candidate.objects.get(pk=candidate_id)
    tasks = Task.objects.filter(question__candidate=candidate)
    return render(request, 'candidates/list_tasks.html', {'candidate': candidate, 'tasks': tasks})


def task_solution(request, task_id):
    task = Task.objects.get(pk=task_id)
    if request.method == 'POST':
        solution_form = TaskSolutionForm(request.POST, instance=task)
        if solution_form.is_valid():
            solution_form.save()
            return redirect('candidate:show_all_candidate')
    else:
        solution_form = TaskSolutionForm()
    return render(request, 'candidates/task_solution.html', {'task': task, 'solution_form': solution_form})

candidates/templates/candidates/list_candidate.html
{% extends 'base.html' %}

{% block candidate %}
{% for candidate in candidates %}
    <li>{{ candidate.full_name }}</li>
    <a href="{% url 'candidate:show_tasks' candidate.id %}">Zadania</a>
{% endfor %}
{% endblock %}


{% block recruiter %}

{% endblock %}

candidates/templates/candidates/list_tasks.html
<h>{{ candidate.full_name }}</h>
{% for task in tasks %}
    <li><a href="{{ task.get_absolute_url }}">{{ task.title }}</a> </li>
        <p>{{ task.content }}</p>
{% endfor %}

candidates/templates/candidates/task_solution.html
<p>{{ task.title }}</p>
{{ task.content }}
<p>{{ task.answer }}</p>

<form method="post">
    {{ solution_form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Zapisz">
</form>