can/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidates.urls', namespace='candidate')),
    path('', include('recruiters.urls', namespace='recruiters')),
    path('tasks/', include('tasks.urls', namespace='task')),
]

recruiters/urls.py
from django.urls import path
from recruiters.views import show_all_recruiters, index, detail_recruiter, add_task, add_task_to_candidate, \
    candidate_list, show_task_candidate, judge_task_candidate

app_name = 'recruiters'


urlpatterns = [
    path('', index, name='index'),
    path('recruiters/', show_all_recruiters, name='show_all_recruiters'),
    path('recruiter/<int:recruiter_id>/', detail_recruiter, name='detail_recruiter'),
    path('taskcandidate/', add_task_to_candidate, name='add_task_to_candidate'),
    path('add-task/', add_task, name='add_task'),
    path('candidates/', candidate_list, name='candidate_list'),
    path('tasks-candidate/<candidate_id>/', show_task_candidate, name='show_task_candidate'),
    path('judge-task/<int:grade_id>/', judge_task_candidate, name='judge_task_candidate'),

]

tasks/urls.py
from django.urls import path
from tasks.views import show_all_task
app_name = 'tasks'

urlpatterns = [
    path('all-tasks/', show_all_task, name='show_all_task')
]

recruiters/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Recruiter(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    class Meta:
        index_together = (('id',),)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('recruiters:detail_recruiter', args=[self.id])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

recruiters/forms.py
from candidates.models import Candidate
from grade.models import Grade
from tasks.models import Task
from django import forms


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['answer']


class AddTaskForm(forms.Select):
    class Meta:
        model = Task
        fields = ('title',)


class AddCandidateForm(forms.Select):
    class Meta:
        model = Candidate
        fields = ('first_name',)


class AddTaskCandidateForm(forms.ModelForm):
    class Meta:
        model = Grade
        exclude = ('value',)
        widgets = {'task': AddTaskForm, 'candidate': AddCandidateForm}


class JudgeTaskForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ['value']

recruiters/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from candidates.models import Candidate
from grade.models import Grade
from recruiters.forms import CreateTaskForm, AddTaskCandidateForm, JudgeTaskForm
from recruiters.models import Recruiter
# Create your views here.



def index(request):
    return render(request, 'base.html')


def show_all_recruiters(request):
    recruiters = Recruiter.objects.all()
    return render(request, 'recruiters/all_recruiters.html', {'recruiters': recruiters})


def detail_recruiter(request, recruiter_id):
    recruiter = Recruiter.objects.get(pk=recruiter_id)
    return render(request, 'recruiters/recruiter.html', {'recruiter': recruiter})


def add_task(request):
    add_task_form = CreateTaskForm(request.POST)
    if request.method == 'POST':
        if add_task_form.is_valid():
            add_task_form.save()

            return redirect('tasks:show_all_task')
    else:
        add_task_form = CreateTaskForm()

    return render(request, 'recruiters/add_task.html', {'add_task_form': add_task_form})


def add_task_to_candidate(request):
    if request.method == 'POST':
        form_grade = AddTaskCandidateForm(request.POST)
        if form_grade.is_valid():
            form_grade.save()
            return redirect('recruiters:add_task_to_candidate')

    else:
        form_grade = AddTaskCandidateForm()
    return render(request, 'recruiters/task_to_candidate.html', {'form_grade': form_grade})


def candidate_list(request):
    candidates = Candidate.objects.all()
    return render(request, 'recruiters/candidate_list.html', {'candidates': candidates})


def show_task_candidate(request, candidate_id):
    candidate = Candidate.objects.get(pk=candidate_id)
    garde = Grade.objects.filter(candidate_id=candidate)
    return render(request, 'recruiters/candidate_tasks_list.html', { 'candidate': candidate, 'garde': garde})


def judge_task_candidate(request, grade_id):
    grade = Grade.objects.get(pk=grade_id)

    if request.method == 'POST':
        form_judge = JudgeTaskForm(request.POST, instance=grade)
        if grade.value:
            messages.error(request, 'zadanie bylo juz oceniane')
        else:
            if form_judge.is_valid():
                form_judge.save()
                messages.success(request, 'zadanie oceniane')
                redirect('recruiters:candidate_list')

    else:
        form_judge = JudgeTaskForm()
    return render(request, 'recruiters/judge_tasks.html', {'form_judge': form_judge, 'grade': grade})

recruiters/templates/recruiters/add_task.html
<p>Dodaj zadanie</p>
<form method="post">
    {{ add_task_form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Zapisz">
</form>

recruiters/templates/recruiters/all_recruiters.html
{% extends 'base.html' %}

{% block candidate %}

{% endblock %}


{% block recruiter %}
{% for recruiter in recruiters %}
    <li><a href="{{ recruiter.get_absolute_url }}">{{ recruiter.full_name }}</a></li>
    {% endfor %}
{% endblock %}

recruiters/templates/recruiters/candidate_list.html
{% for candidate in candidates %}
    <li>{{ candidate.full_name }}</li>
    <li><a href="{% url 'recruiters:show_task_candidate' candidate.id %}">Lista zadań</a></li>
{% endfor %}

recruiters/templates/recruiters/candidate_tasks_list.html
{{ candidate.full_name }}
{% for g in garde %}
{#    <li>{{ g.task.title }}</li>#}
{#        <p>{{ g.task.content }}</p>#}
{#    {% if g.value is not None %}#}
{#        Ocena: {{ g.value }}#}
{#    {% else %}#}

      <ul>{{ g.task.title }} <a href="{{ g.get_absolute_url }}">Oceń</a></ul>
{#    {% endif %}#}
{% endfor %}

recruiters/templates/recruiters/judge_tasks.html
{{ grade.candidate.full_name }}
<h1>{{ grade.task.title}}</h1>
<p>{{ grade.task.content}}</p>
{{ grade.task.answer }}


<form method="post">
    {{ form_judge.as_p }}
    {% csrf_token %}
    <input type="submit" value="Oceń">
</form>

recruiters/templates/recruiters/recruiter.html
{% extends 'base.html' %}

{% block candidate %}

{% endblock %}

{% block recruiter %}

{% endblock %}

{% block tasks %}
    Rekruter: {{ recruiter.full_name }}
    <p><a href="{% url 'recruiters:add_task' %}">Dodaj zadanie</a> </p>
    <p><a href="{% url 'tasks:show_all_task' %}" >Lista zadań</a></p>
    <p><a href="{% url 'recruiters:add_task_to_candidate'%}">Dodaj kandydatom pytania</a> </p>
    <p><a href="{% url 'recruiters:candidate_list' %}">Lista kandydatów</a> </p>



{% endblock %}

recruiters/templates/recruiters/task_to_candidate.html
<form method="post">
    {{ form_grade.as_p }}
    {% csrf_token %}
    <input type="submit" value="Zapisz">
</form>